package es.gonzagile.jmockload.generators.dumb;

import es.gonzagile.jmockload.constraints.FieldConstraint;
import es.gonzagile.jmockload.generators.ValueGenerator;

import java.lang.reflect.Array;
import java.util.List;
import java.util.Random;

/**
 * Sets an Array of primitives with values generated by the ValueGenerator to the specified field. The array's len can be set,
 * as well as a range of min and max possible array's lengths.
 */
public class RandomPrimitiveArrayGenerator<T> implements ValueGenerator<Object> {
    private final Class<T> primitiveType;
    private final ValueGenerator<T> valuesGenerator;
    private final int minlen;
    private final int maxlen;
    private final Random r = new Random();

    /**
     * Constructor that generates an array of primitives with a default size of 2.
     * @param primitiveType The type of the primitives stored in the array.
     * @param valuesGenerator The ValueGenerator implementation to generate the values of the array.
     */
    public RandomPrimitiveArrayGenerator(Class<T> primitiveType, ValueGenerator<T> valuesGenerator) {
        this(primitiveType, valuesGenerator, 2, 2);
    }

    /**
     * Constructor that generates an array of primitives with a default size of 2.
     * @param primitiveType The type of the primitives stored in the array.
     * @param valuesGenerator The ValueGenerator implementation to generate the values of the array.
     * @param size The size of the array.
     */
    public RandomPrimitiveArrayGenerator(Class<T> primitiveType, ValueGenerator<T> valuesGenerator, int size) {
        this(primitiveType, valuesGenerator, size, size);
    }

    /**
     * Constructor that generates an array of primitives with a default size of 2.
     * @param primitiveType The type of the primitives stored in the array.
     * @param valuesGenerator The ValueGenerator implementation to generate the values of the array.
     * @param minlen The minimum possible size of the array.
     * @param maxlen The maximus non-inclusive possible size of the array.
     */
    public RandomPrimitiveArrayGenerator(Class<T> primitiveType, ValueGenerator<T> valuesGenerator, int minlen, int maxlen) {
        if (!primitiveType.isPrimitive()) {
            throw new IllegalArgumentException("Non-primitives are not allowed: " + primitiveType);
        }
        this.primitiveType = primitiveType;
        this.valuesGenerator = valuesGenerator;
        this.minlen = minlen;
        this.maxlen = maxlen;
    }

    @Override
    public Object generate() {
        return this.generate(0, List.of());
    }

    @Override
    public Object generate(int index) {
        return this.generate(index, List.of());
    }

    @Override
    public Object generate(int index, List<FieldConstraint> constraints) {
        int len = minlen == maxlen ? minlen : r.nextInt(minlen, maxlen);
        Object array = Array.newInstance(primitiveType, len);
        for (int i = 0; i < len; i++) {
            Object value = valuesGenerator.generate(i, constraints);
            Array.set(array, i, value);
        }
        return array;
    }
}
